# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete_update.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(974, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 10, 671, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(16)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(370, 60, 591, 471))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 90, 321, 151))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(8, 17, 10, 5)
        self.formLayout.setHorizontalSpacing(15)
        self.formLayout.setVerticalSpacing(18)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineAdSoyad = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineAdSoyad.setMinimumSize(QtCore.QSize(0, 0))
        self.lineAdSoyad.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineAdSoyad.setFont(font)
        self.lineAdSoyad.setText("")
        self.lineAdSoyad.setObjectName("lineAdSoyad")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineAdSoyad)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineBolum = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineBolum.setBaseSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineBolum.setFont(font)
        self.lineBolum.setText("")
        self.lineBolum.setObjectName("lineBolum")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineBolum)
        self.lineNumara = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineNumara.setBaseSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineNumara.setFont(font)
        self.lineNumara.setText("")
        self.lineNumara.setReadOnly(True)
        self.lineNumara.setObjectName("lineNumara")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineNumara)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 270, 321, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(18, 5, 10, 6)
        self.verticalLayout.setSpacing(9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnGuncelle = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnGuncelle.setMinimumSize(QtCore.QSize(0, 50))
        self.btnGuncelle.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnGuncelle.setFont(font)
        self.btnGuncelle.setStyleSheet("QPushButton:hover{\n"
"background-color: #5EABD6;\n"
"}\n"
"QPushButton{\n"
"    border-radius:10px;\n"
"    border:2px solid black;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnGuncelle.setIcon(icon)
        self.btnGuncelle.setIconSize(QtCore.QSize(33, 30))
        self.btnGuncelle.setObjectName("btnGuncelle")
        self.verticalLayout.addWidget(self.btnGuncelle)
        self.btnSil = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnSil.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnSil.setFont(font)
        self.btnSil.setStyleSheet("QPushButton:hover{\n"
"background-color: #A31D1D;\n"
"}\n"
"QPushButton{\n"
"border-radius: 10px;\n"
"border:2px solid black;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSil.setIcon(icon1)
        self.btnSil.setIconSize(QtCore.QSize(25, 30))
        self.btnSil.setObjectName("btnSil")
        self.verticalLayout.addWidget(self.btnSil)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 974, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Öğrenci Kayıt  🔄 Güncelleme ve ❌  Silme Formu"))
        self.label_4.setText(_translate("MainWindow", "Numara"))
        self.label_2.setText(_translate("MainWindow", "Ad Soyad"))
        self.label_3.setText(_translate("MainWindow", "Bölüm"))
        self.btnGuncelle.setText(_translate("MainWindow", "Güncelle"))
        self.btnSil.setText(_translate("MainWindow", "Sil"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
